### ISSUE TITLE
add proper error messages

### ISSUE THREAD

**Issue by Kumaru01** [jsmsj/GdriveCloneWeb#1]
It's shows only started cloning.logs also checked response code 200.

**Comment by jsmsj** [comment]
the source and destination urls must be google drive links.

acceptable links: `https://drive.google.com/drive/u/2/folders/folderid`

non acceptable links: `https://drive.google.com/drive/u/2/my-drive` or any other link.

for cloning to your own account's drive make a folder in your drive and add that folder's url to destination.

And yes i still have to add the error logs. i will do that soon

**Comment by Kumaru01** [comment]
Ya I got ....
